<!DOCTYPE bookstore [
<!ELEMENT bookstore (book)+ >
<!ELEMENT book (title,(author|publisher),year,price)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT price (#PCDATA)>
]>
<bookstore>
	<book>
		<title> Angels and Demons </title>
		<publisher> asdfsadf </publisher>
		<year> 2005 </year>
		<price> $120</price>
	 </book>
	<book>
		<title> Harry Potter </title>
		<author> J K Rowling </author>
		<year> 2001 </year>
		<price> $100 </price>
	</book>
	</bookstore>
	<book category="Cooking">
		<title> Breakfast in 5 mins </title>
		<author> Tarla Dalal </author>
		<year> 2012 </year>
		<price> $80 </price>
	</book>
	<book category="Suspense">
		<title> Digital Fortress </title>
		<author> Dan Brown </author>
		<year> 2004 </year>
		<price> $120 </price>
	</book>
	
</bookstore>